version: "3.0"
services:
  http-client-requests:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "http-client-requests"
      MODULE_TYPE: "Input"
      URLS: "https://catfact.ninja/fact"
      METHOD: "GET"
      AUTH_TOKEN: ""
      POLL_INTERVAL: "5"
      PAYLOAD: ""
      HEADER: ""
    ports:
      - 80:80
